[pytest]
minversion = 9.1.1
testpaths = tests
addopts = -ra -v --basetemp=.pytest_temp
norecursedirs =
    .pytest_temp
    .hypothesis
    releases
    build
    dist
    _archive
    .venv
    venv
    __pycache__
    codex_build
